language: node_js
node_js:
  - "0.10"
branches:
  only:
    - master
before_script:
  - npm install -g bower
  - npm install phantomjs
  - npm install -g karma
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start